import { SearchProfileItem } from 'src/app/model/search-profile-item';

export class SearchProfileConfiguration {
  public static ITEMS: SearchProfileItem[] = [
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_BABY', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_GIRL', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_BOY', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_TEENAGER_GIRL', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_TEENAGER_BOY', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_ADULT_WOMAN', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_ADULT_MAN', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_ELDER_WOMAN', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),
    new SearchProfileItem('SEARCH_PROFILE_GENDER_AGE_ELDER_MAN', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_GENDER_AND_AGE'),

    new SearchProfileItem('SEARCH_PROFILE_CHARACTERISTICS_ACTIVE', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_CHARACTERISTICS'),
    new SearchProfileItem('SEARCH_PROFILE_CHARACTERISTICS_CREATIVE', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_CHARACTERISTICS'),
    new SearchProfileItem('SEARCH_PROFILE_CHARACTERISTICS_CLEVER', 'PEOPLE', 'SEARCH_PROFILE_CATEGORY_CHARACTERISTICS'),

  ];
}
