export enum ModeratedTeaserMode {
  START_WITH_SMALL_END_WITH_BIG = 'START_WITH_SMALL_END_WITH_BIG',
  START_WITH_BIG_END_WITH_SMALL = 'START_WITH_BIG_END_WITH_SMALL',
  THREE_TIMES_BIG = 'THREE_TIMES_BIG',
  ALL_SMALL = 'ALL_SMALL'
}
